apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-gke
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask-cont
        image: us-central1-docker.pkg.dev/orbital-age-427911-k0/flask-pdf/flaskdemo1:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: flaskdemo1
spec:
  selector:
    app: flask
  ports:
  - port: 8080
  type: LoadBalancer